# Resolve react_native_pods.rb using node and allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported  # Ensure the platform is set according to your project requirements

prepare_react_native_project!

# Manage framework linkage based on environment
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'GOParkProject' do
  config = use_native_modules!

  # # Include Mapbox-iOS-SDK for both Debug and Release configurations
  # pod 'Mapbox-iOS-SDK', :configurations => ['Debug', 'Release']

  # Use React Native setup with an absolute path to your app
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'GOParkProjectTests' do
    inherit! :complete
    # Pods for testing (if necessary)
  end

  post_install do |installer|
    # Custom React Native post-install hook
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false  # Disable macOS Catalyst if not needed
    )

    # Exclude 'arm64' architecture for the iOS Simulator to avoid conflicts
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.name == 'Debug'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
      end
    end
  end
end
